// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLf2aNq9pSWshmpxudYLW25XDhdeVscqY',
    appId: '1:304786236205:web:b4d0deb35d2243cbbda9a4',
    messagingSenderId: '304786236205',
    projectId: 'flutter-chess-2ed7d',
    authDomain: 'flutter-chess-2ed7d.firebaseapp.com',
    databaseURL: 'https://flutter-chess-2ed7d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-chess-2ed7d.appspot.com',
    measurementId: 'G-BJTG07W4CH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfy8FRl_Yn69z2wfP8qszUq6r39H1VEg4',
    appId: '1:304786236205:android:f5f47584b262a124bda9a4',
    messagingSenderId: '304786236205',
    projectId: 'flutter-chess-2ed7d',
    databaseURL: 'https://flutter-chess-2ed7d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-chess-2ed7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2nK3pQyhWm94xuHYT3Q2thW9E21n5J4',
    appId: '1:304786236205:ios:c809ad978eff143abda9a4',
    messagingSenderId: '304786236205',
    projectId: 'flutter-chess-2ed7d',
    databaseURL: 'https://flutter-chess-2ed7d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-chess-2ed7d.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO2nK3pQyhWm94xuHYT3Q2thW9E21n5J4',
    appId: '1:304786236205:ios:45f3fe1f30905de0bda9a4',
    messagingSenderId: '304786236205',
    projectId: 'flutter-chess-2ed7d',
    databaseURL: 'https://flutter-chess-2ed7d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-chess-2ed7d.appspot.com',
    iosBundleId: 'com.example.client.RunnerTests',
  );
}
